
CREATE TABLE IF NOT EXISTS hits (
    id bigint generated by default as identity not null,
    app VARCHAR(32) NOT NULL,
    uri VARCHAR(2048) NOT NULL,
    ip VARCHAR(40) NOT NULL,
    datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (id)
);