version: '3.1'
services:
  stats-server:
    build: stat_svc/stat_server
    image: ewm-stat
    container_name: ewm-stat
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    volumes:
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreWithMeStat?user=user&password=user
      - TZ=Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6543:5432"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=exploreWithMeStat
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - TZ=Europe/Moscow

  ewm-service:
    build: main_svc
    image: ewm-main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/exploreWithMe?user=userdb&password=userdb
      - STAT_SERVER_URL=http://ewm-stat:9090
      - TZ=Europe/Moscow

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=exploreWithMe
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=userdb
      - TZ=Europe/Moscow